version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "3011:3011"
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

  frontend:
    build:
      context: ./apurba-blog-app
      dockerfile: frontend.dockerfile
    ports:
      - "3009:3009"
    volumes:
      - ./apurba-blog-app:/app
    command: ["npx", "http-server", "-p", "3009"]

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
